# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Hongtao's Notebook 
tagline:             'Machine Learning, Big Data, & Cloud Computing,'
description:         "Hongtao Yu    linkedin.com/in/htaoyu "
url:                 https://htaoyu1.github.io
baseurl:             ''
paginate:            1


markdown:            kramdown
highlighter:         rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# About/contact
author:
  name:              Hongtao Yu 
  url:               https://htaoyu1.github.io
  email:             htaoyu1@gmail.com 

# Custom vars
version:             1.0.0

plugins:     
  - jekyll-paginate

